# Generated by Django 4.2.1 on 2023-09-05 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=20, verbose_name='customer_name')),
                ('customer_phone', models.IntegerField(max_length=15, verbose_name='customer_phone')),
                ('address', models.CharField(max_length=205, verbose_name='address')),
                ('zip_code', models.IntegerField(max_length=5, verbose_name='zip_code')),
                ('apt', models.CharField(max_length=20, verbose_name='apt')),
                ('city', models.CharField(max_length=20, verbose_name='city')),
                ('state', models.CharField(max_length=10, verbose_name='state')),
                ('total_price', models.FloatField(verbose_name='total_price')),
                ('total_quantity', models.IntegerField(verbose_name='total_quantity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_user_order', to='users.users')),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
